// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcjaamsswjibkvzlpbds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjamFhbXNzd2ppYmt2emxwYmRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjExODMsImV4cCI6MjA2NTQ5NzE4M30.IyjJ0hvxvEqAk5fxmcWP17OKNyUxQGcTYxR1ar8ZXeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);